const POLL_MS = 1000;

function lang() {
  const value = String(document.documentElement?.lang || navigator.language || "en").toLowerCase();
  if (value.startsWith("ko")) return "ko";
  if (value.startsWith("zh")) return "zh";
  return "en";
}
const COPY = {
  ko:{title:"KO 도어 제어",desc:"시동 ON · P단 · 완전정지 · CAN 정상 · 주행보조 해제 상태에서만 동작합니다.",lock:"문 잠금",unlock:"잠금 해제",enabled:"사용 가능",disabled:"위의 ‘KO 도어 제어 허용’을 켜세요.",config:"검증된 /data/ko/door_can.json이 필요합니다.",unsafe:"현재 차량 상태에서는 도어 명령을 보낼 수 없습니다.",working:"명령 전송 중…",okLock:"도어 잠금 명령을 전송했습니다.",okUnlock:"도어 잠금 해제 명령을 전송했습니다.",confirmLock:"현재 차량의 도어 잠금 명령을 전송할까요?",confirmUnlock:"현재 차량의 도어 잠금 해제 명령을 전송할까요?",failed:"도어 명령 실패"},
  en:{title:"KO Door Control",desc:"Works only with ignition ON, Park, standstill, valid CAN, and driver assistance disengaged.",lock:"Lock doors",unlock:"Unlock doors",enabled:"Ready",disabled:"Enable ‘Allow KO Door Control’ above.",config:"A verified /data/ko/door_can.json is required.",unsafe:"Door commands are blocked by the current vehicle state.",working:"Sending command…",okLock:"Door lock command sent.",okUnlock:"Door unlock command sent.",confirmLock:"Send the door lock command to the vehicle?",confirmUnlock:"Send the door unlock command to the vehicle?",failed:"Door command failed"},
  zh:{title:"KO车门控制",desc:"仅在点火开启、P挡、完全静止、CAN正常且驾驶辅助未接管时工作。",lock:"锁车",unlock:"解锁",enabled:"可用",disabled:"请先开启上方“允许KO车门控制”。",config:"需要已验证的/data/ko/door_can.json。",unsafe:"当前车辆状态不允许发送车门命令。",working:"正在发送命令…",okLock:"已发送锁车命令。",okUnlock:"已发送解锁命令。",confirmLock:"是否向车辆发送锁车命令？",confirmUnlock:"是否向车辆发送解锁命令？",failed:"车门命令失败"}
};
function t(k){const x=COPY[lang()]||COPY.en;return x[k]||COPY.en[k]||k;}
function blocked(l){return !l||!l.ignition||!l.park||Math.abs(Number(l.v_ego)||0)>0.1||!l.can_valid||l.engaged;}
function statusText(s){if(!s?.door_control_enabled)return t("disabled");if(!s?.door_config_present)return t("config");if(blocked(s.live))return t("unsafe");return t("enabled");}
async function requestJson(url,options={}){const r=await fetch(url,{cache:"no-store",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});let p={};try{p=await r.json();}catch{}if(!r.ok||p?.ok===false){throw new Error(p?.error||(Array.isArray(p?.blocked)?p.blocked.join(", "):`HTTP ${r.status}`));}return p;}
function build(root){const d=root.ownerDocument,s=d.createElement("section");s.className="setting-section-block ui-stagger-item";s.dataset.settingsExtensionPanel="ko-door-control";const c=d.createElement("div");c.className="setting-group-card";c.innerHTML=`<div class="setting-profile-card__rows"><div class="setting-profile-row setting-profile-row--name"><div><strong class="setting-profile-row__label" data-role="title"></strong><p class="muted mt-sm" data-role="desc"></p></div><span class="chip chip--compact" data-role="state" role="status"></span></div></div><div class="ui-action-grid"><button type="button" class="smallBtn" data-role="lock"></button><button type="button" class="smallBtn" data-role="unlock"></button></div>`;s.appendChild(c);root.appendChild(s);c.querySelector('[data-role="title"]').textContent=t("title");c.querySelector('[data-role="desc"]').textContent=t("desc");c.querySelector('[data-role="lock"]').textContent=t("lock");c.querySelector('[data-role="unlock"]').textContent=t("unlock");return{section:s,card:c};}
export function mountKoDoorPanel({root,lifecycle}){const v=build(root),state=v.card.querySelector('[data-role="state"]'),lock=v.card.querySelector('[data-role="lock"]'),unlock=v.card.querySelector('[data-role="unlock"]');let st=null,busy=false;function render(){const ready=Boolean(st?.door_control_enabled&&st?.door_config_present&&!blocked(st?.live));lock.disabled=busy||!ready;unlock.disabled=busy||!ready;state.textContent=busy?t("working"):statusText(st);state.className="chip chip--compact"+(ready&&!busy?" chip--success":st?" chip--warning":"");}async function refresh(){if(busy||lifecycle.destroyed||document.hidden)return;try{st=await requestJson("/api/ko/vehicle/status");render();}catch(e){st=null;state.textContent=`${t("failed")}: ${e.message}`;state.className="chip chip--compact chip--warning";lock.disabled=true;unlock.disabled=true;}}async function command(a){if(busy)return;const msg=a==="lock"?t("confirmLock"):t("confirmUnlock");const ok=typeof globalThis.appConfirm==="function"?await globalThis.appConfirm(msg,{confirmLabel:a==="lock"?t("lock"):t("unlock")}):globalThis.confirm(msg);if(!ok)return;busy=true;render();try{await requestJson(`/api/ko/door/${a}`,{method:"POST",body:"{}"});globalThis.showAppToast?.(a==="lock"?t("okLock"):t("okUnlock"));}catch(e){globalThis.showAppToast?.(`${t("failed")}: ${e.message}`,{tone:"error"});}finally{busy=false;await refresh();}}const onL=()=>void command("lock"),onU=()=>void command("unlock");lock.addEventListener("click",onL);unlock.addEventListener("click",onU);lifecycle.addCleanup(()=>lock.removeEventListener("click",onL));lifecycle.addCleanup(()=>unlock.removeEventListener("click",onU));const onV=()=>{if(!document.hidden)void refresh();};document.addEventListener("visibilitychange",onV);lifecycle.addCleanup(()=>document.removeEventListener("visibilitychange",onV));lifecycle.setIntervalWhileMounted(refresh,POLL_MS);render();void refresh();return{root:v.section,sync(){render();},destroy(){v.section.remove();}};}
